### ISSUE TITLE
Extra generic?

### ISSUE THREAD

**Issue by bicarlsen** [JonasKruckenberg/tauri-sys#21]
In the [`tauri_sys::window::WebviewWindow.listen`](https://github.com/JonasKruckenberg/tauri-sys/blob/904450cffe9687fdd4c5163077550edffa650a68/src/window.rs#L797) method there are two generics:
`pub async fn listen<T, H>(&self, event: &str) -> crate::Result<impl Stream<Item = Event<T>>>`.
It is clear what `T` is doing, but I am unclear as to what `H` is used for, as I don't see it referenced anywhere.

**Comment by JonasKruckenberg** [comment]
Yeah I noticed that a few days ago as well, it's a good ol copy paste issue, that generic does nothing 😁

**Comment by JonasKruckenberg** [comment]
removed the extra generic now!
