### ISSUE TITLE
A way to get proper errors

### ISSUE THREAD

**Issue by jrouaix** [JonasKruckenberg/tauri-sys#26]
Hello, 

Whould it be nice to have access to errors when `invoke` ?

like :
`pub mod error;` in the lib ?

and a simple :
```rust
pub enum Error {
    #[error("JS Binding: {0:?}")]
    Binding(#[from] JsValue),
```

Same is perhaps better on `Error::Serde` (the #[from] part without transforming the value)

I tried to change that on a fork but the builds & tests didn't get far, is the project looking for maintainers ?

**Comment by JonasKruckenberg** [comment]
The error enum is public now, a larger change to the way custom errors are propagated is a bit more tricky, see #18 for details on that.
