### ISSUE TITLE
process::exit not working: RuntimeError: Unreachable code should not be executed

### ISSUE THREAD

**Issue by kzhui125** [JonasKruckenberg/tauri-sys#44]
```rs
use leptos::*;
use tauri_sys::process;

spawn_local(async move {
    process::exit(1).await;
})
```

<img width="507" alt="image" src="https://github.com/JonasKruckenberg/tauri-sys/assets/11925432/b1edb925-d24a-40fc-8370-c30cd7df8687">

**Comment by JonasKruckenberg** [comment]
Without any context like this it's hard to pin down what's going on, but have you configured your allowlist to allow the `process` module and `exit` function?

**Comment by kzhui125** [comment]
After change `tauri.conf.json` and `Cargo.toml`, it works.

Thanks, but I think the error message is confusing.

```json
"process": {
    "all": true
}
```

```
"process-all"
```

**Comment by JonasKruckenberg** [comment]
Yeah agreed, tbf though you should be getting a second error message from Tauri telling you what's wrong, but maybe we can improve this error message too

**Comment by kzhui125** [comment]
> Yeah agreed, tbf though you should be getting a second error message from Tauri telling you what's wrong, but maybe we can improve this error message too

How can I get second error message from Tauri? I only get error from frontend dev tools now.

code:

[temp1.zip](https://github.com/JonasKruckenberg/tauri-sys/files/13930592/temp1.zip)
