### ISSUE TITLE
Dependency on `wasm-bindgen` feature `serde_json` can cause circular dependency

### ISSUE THREAD

**Issue by bicarlsen** [JonasKruckenberg/tauri-sys#52]
Currently the crate depends on `wasm-bindgen = { version = "0.2.89", features = ["serde_json"] }` which can cause a circular dependency as described in [aHash](https://github.com/tkaitchuck/aHash/issues/95) and [getrandom](https://github.com/rust-random/getrandom/issues/231), and discussed further in [wasm-bindgen](https://github.com/rustwasm/wasm-bindgen/pull/3031).

I removed this feature dependency and played with the crate a bit, and everything still seems to work.

## Reproduction
I ran into this issue when trying to incorporate [SurrealDB](https://github.com/surrealdb/surrealdb) into my Tauri app.

Including both `surrealdb` and `tauri-sys` caused the issue.

## Patched branch
https://github.com/bicarlsen/tauri-sys/tree/fix/wasm_bindgen_serde

**Comment by emirror-de** [comment]
I ran into the same situation and can confirm that your patched branch works for me too. It would be awesome to get this integrated.

**Comment by Alex222222222222** [comment]
I also ran into the same issue when I enable the feature `serde-serialize` of `wasm-bindgen`.

Removed the feature also works for me.

**Comment by bicarlsen** [comment]
This should be resolved with PR #56, please raise another issue if you continue to run into problems.
